import React,{useEffect,useRef,useState} from 'react';
import {MessageSquare,Send,Mic,Volume2,Trash2,X} from 'lucide-react';
import {request,useSession} from './session';
import {tr,LanguageSelector,i18next} from './i18n';
type Entry={id:string;text:string;reply:string;language:string;source:string;created_at:number};
/** Buffered/validated SSE responses, scoped history and optional browser voice controls. */
export default function ChatPanel({floating=false}:{floating?:boolean}){
 const {user}=useSession();const [open,setOpen]=useState(!floating),[history,setHistory]=useState<Entry[]>([]),[text,setText]=useState(''),[reply,setReply]=useState(''),[source,setSource]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[listening,setListening]=useState(false);const recognition=useRef<any>(null),abort=useRef<AbortController|null>(null);
 useEffect(()=>{if(open)request<Entry[]>('/chat/history').then(h=>setHistory(h.reverse())).catch(e=>setError(e.message));},[open]);
 useEffect(()=>()=>{recognition.current?.stop();abort.current?.abort();window.speechSynthesis?.cancel();},[]);
 async function send(event?:React.FormEvent,value?:string){event?.preventDefault();const prompt=(value??text).trim();if(!prompt||busy)return;setBusy(true);setError('');setReply('');setSource('');setText('');abort.current=new AbortController();
  try{
   await request('/consent'); // Refresh/expire the cookie session through shared transport first.
   const response=await fetch('/api/chat',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:prompt,language:i18next.language,stream:true}),signal:abort.current.signal});
   if(!response.ok){const body=await response.json();throw Error(body.detail||tr('Request failed'));}
   if(!response.body)throw Error('Streaming is unavailable in this browser');
   const reader=response.body.getReader(),decoder=new TextDecoder();let buffer='',complete='',metadata={id:'',source:'',language:i18next.language};
   while(true){const {done,value}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const events=buffer.split('\n\n');buffer=events.pop()||'';for(const block of events){const type=block.match(/event: (\w+)/)?.[1],data=block.match(/data: (.+)/)?.[1];if(!data)continue;const parsed=JSON.parse(data);if(type==='metadata'){metadata=parsed;setSource(parsed.source);}if(type==='token'){complete+=parsed.text;setReply(complete);}}}
   setHistory(h=>[...h,{id:metadata.id,text:prompt,reply:complete,language:metadata.language,source:metadata.source,created_at:Date.now()/1000}]);setReply('');
  }catch(e){setError(e instanceof Error?e.message:tr('Request failed'));setText(prompt);}finally{setBusy(false);}
 }
 function voice(){const browser=window as any;const Recognition=browser.SpeechRecognition||browser.webkitSpeechRecognition;if(!Recognition){setError('Voice input is not supported in this browser');return;}if(listening){recognition.current?.stop();setListening(false);return;}const r=new Recognition();recognition.current=r;r.lang=({en:'en-IN',ta:'ta-IN',hi:'hi-IN',te:'te-IN',ml:'ml-IN',kn:'kn-IN',es:'es-ES',fr:'fr-FR',ar:'ar-SA'} as Record<string,string>)[i18next.language]||'en-IN';r.interimResults=false;r.onresult=(e:any)=>setText(e.results[0][0].transcript);r.onerror=()=>{setError('Voice permission or recognition failed');setListening(false);};r.onend=()=>setListening(false);try{r.start();setListening(true);}catch{setError('Voice permission or recognition failed');setListening(false);}}
 function speak(){if(!window.speechSynthesis){setError('Voice output is not supported in this browser');return;}window.speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(history.at(-1)?.reply||reply);utterance.lang=i18next.language;window.speechSynthesis.speak(utterance);}
 if(floating&&!open)return <button className="chat-launcher" aria-label={tr('Assistant')} onClick={()=>setOpen(true)}><MessageSquare size={22}/><span>{tr('Assistant')}</span></button>;
 return <section className={'chat-panel panel '+(floating?'floating-chat':'')}><div className="panel-heading"><div><h3><MessageSquare size={17}/>{tr('Assistant')}</h3><p>{tr('AI assistant, not a doctor')}</p></div>{floating&&<button className="link" aria-label={tr('Close')} onClick={()=>setOpen(false)}><X size={18}/></button>}</div><LanguageSelector/><div className="chat-messages" aria-live="polite">{!history.length&&!busy&&<div className="empty"><MessageSquare size={27}/><p>{tr('Ask about your report or the research workflow.')}</p></div>}{history.map(entry=><React.Fragment key={entry.id}><div className="chat-question">{entry.text}</div><div className="chat-answer">{entry.reply}<small>{entry.source}</small></div></React.Fragment>)}{busy&&<div className="chat-answer">{reply||tr('Please wait…')}<small>{source}</small></div>}</div><div className="suggestions">{['Explain my result','What does confidence mean?','What should I ask my doctor?'].map(q=><button key={q} disabled={busy} onClick={()=>void send(undefined,tr(q))}>{tr(q)}</button>)}</div>{error&&<div className="alert" role="alert">{error}</div>}<form className="chat-form" onSubmit={send}><label><span className="sr-only">{tr('Send message')}</span><textarea rows={2} maxLength={2000} value={text} onChange={e=>setText(e.target.value)} placeholder={tr('Ask a research question…')}/></label><button className="primary" aria-label={tr('Send message')} disabled={busy||!text.trim()}><Send size={17}/></button></form><div className="chat-actions"><button aria-label={tr('Voice input')} onClick={voice}><Mic size={14}/>{listening?tr('Stop'):tr('Voice input')}</button><button onClick={speak}><Volume2 size={14}/>{tr('Read aloud')}</button><button disabled={busy} onClick={async()=>{try{await request('/chat/history',undefined,'DELETE');setHistory([]);setError('');}catch(e){setError(e instanceof Error?e.message:tr('Request failed'));}}}><Trash2 size={14}/>{tr('Delete chat history')}</button></div><p className="chat-footnote">{tr('Research prototype. Not for diagnosis or treatment.')}</p></section>;
}
