import React,{useEffect,useState} from 'react';
import {Activity,ArrowRight,FileText,GitMerge,Shield,Check,Download} from 'lucide-react';
import {request,useSession} from './session';
export type Feature={name:string;numeric:boolean;unit:string;min:number|null;max:number|null;help:string};
export type Schema={id:string;name:string;features:Feature[]};
export type Report={id:string;patient_id:string;dataset_id:string;dataset_name:string;sample:Record<string,unknown>;created_at:number;status:string;warnings:string[];classical:{probability:number;name:string;model_id:string};quantum:{probability:number;name:string;model_id:string};consensus?:{agreement:boolean;probability_gap:number;prediction_set:number[];uncertainty_level:string;triage:string;reasons:string[]};patient_view:{summary:string;next_step:string;top_features:unknown[]};reviews:{doctor_name:string;action:string;note:string;timestamp:number}[];explanation?:{method:string;features:{feature:string;value:number}[];base_value:number;probability:number};language:string};
const pct=(n:number)=>`${(n*100).toFixed(1)}%`;

/** Consent-scoped submissions and ownership-scoped review list. */
export default function ClinicalPanel({page}:{page:string}){
 const {user}=useSession();const [schemas,setSchemas]=useState<Schema[]>([]),[datasetId,setDatasetId]=useState(''),[sample,setSample]=useState<Record<string,unknown>>({}),[reports,setReports]=useState<Report[]>([]),[selected,setSelected]=useState<Report|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[note,setNote]=useState(''),[lab,setLab]=useState<any>(null),[override,setOverride]=useState(0);
 const schema=schemas.find(s=>s.id===datasetId);
 const refresh=()=>request<Report[]>('/reports').then(setReports).catch(e=>setError(e.message));
 useEffect(()=>{request<Schema[]>('/clinical/datasets').then(d=>{setSchemas(d);setDatasetId(v=>v||d.find(x=>x.id==='heart')?.id||d[0]?.id||'');}).catch(e=>setError(e.message));refresh();},[page]);
 async function action(fn:()=>Promise<void>){setBusy(true);setError('');try{await fn();}catch(e){setError(e instanceof Error?e.message:'Request failed');}finally{setBusy(false);}}
 const fill=()=>{if(schema)setSample(Object.fromEntries(schema.features.map(f=>[f.name,f.numeric?Number((((f.min||0)+(f.max||0))/2).toFixed(4)):'synthetic'])));};
 const detail=async(id:string)=>{setSelected(await request<Report>('/reports/'+id));setNote('');};
 const review=async(action:string)=>{if(!selected)return;const updated=await request<Report>(`/reports/${selected.id}/review`,{action,note,override_label:action==='override'?override:undefined});setSelected(updated);setNote('');await refresh();};
 return <><div className="clinical-toolbar"><label>Research dataset<select value={datasetId} onChange={e=>{setDatasetId(e.target.value);setSample({});setLab(null);}}>{schemas.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><span className="tag">ANONYMIZED / SYNTHETIC DATA ONLY</span></div>{error&&<div className="alert" role="alert">{error}</div>}
 {page==='Measurements'&&<section className="panel"><div className="panel-heading"><div><h3>Explore your measurements</h3><p>Use dataset-compatible values. This form does not diagnose disease.</p></div><button className="secondary" onClick={fill}>Fill synthetic demo</button></div><div className="measurement-grid">{schema?.features.map(f=><label key={f.name}>{f.name}<span className="unit">{f.unit}</span><input required type={f.numeric?'number':'text'} step="any" value={String(sample[f.name]??'')} onChange={e=>setSample(v=>({...v,[f.name]:f.numeric?e.target.value===''?'':Number(e.target.value):e.target.value}))}/><small>{f.help}</small></label>)}</div><p className="muted">Research consent is required. Range warnings describe the benchmark, not healthy or unhealthy ranges.</p><button className="primary" disabled={busy||!schema||Object.keys(sample).length!==schema.features.length} onClick={()=>action(async()=>{const r=await request<Report>('/reports',{dataset_id:datasetId,sample});setSelected(r);await refresh();})}><Activity size={16}/>Create research report</button></section>}
 {(page==='My reports'||page==='Review queue')&&<section className="panel"><div className="panel-heading"><h3>{user?.role==='patient'?'Your research reports':'Assigned participant review queue'}</h3><span className="tag">{reports.length} REPORTS</span></div>{!reports.length&&<div className="empty"><FileText size={28}/><p>No reports yet. Submit measurements to begin.</p></div>}<div className="report-list">{reports.map(r=><button key={r.id} onClick={()=>action(()=>detail(r.id))}><span className="report-icon"><FileText size={20}/></span><span><strong>{r.dataset_name}</strong><small>{new Date(r.created_at*1000).toLocaleString()}</small></span><span className={'status '+r.status}>{r.status==='needs_review'?'Your doctor will review':r.status==='reviewed'?'Reviewed':'Submitted'}</span><ArrowRight size={16}/></button>)}</div></section>}
 {page==='Consensus Lab'&&<><section className="panel"><div className="panel-heading"><div><h3>Two models. One test set.</h3><p>Measured disagreement and error association on an untouched holdout.</p></div><button className="primary" disabled={busy} onClick={()=>action(async()=>setLab(await request('/consensus/lab/'+datasetId)))}><GitMerge size={16}/>Analyze agreement</button></div>{lab?<><div className="stats"><section><div>Agreement rate</div><strong>{pct(lab.agreement_rate)}</strong><small>{lab.samples} held-out rows</small></section><section><div>Disagreement cases</div><strong>{lab.disagreement_count}</strong><small>Actual measured count</small></section><section><div>Error correlation</div><strong>{lab.disagreement_error_correlation===null?'Undefined':lab.disagreement_error_correlation.toFixed(3)}</strong><small>Descriptive association only</small></section></div><p className="muted">Any-model error rate when agreeing: {lab.error_rate_when_agree===null?'N/A':pct(lab.error_rate_when_agree)}. When disagreeing: {lab.error_rate_when_disagree===null?'N/A':pct(lab.error_rate_when_disagree)}.</p><div className="table-scroll"><table><thead><tr><th>Holdout row</th><th>Actual label</th><th>Classical probability</th><th>Quantum probability</th><th>Either model wrong</th></tr></thead><tbody>{lab.cases.map((c:any)=><tr key={c.index}><td>{c.index}</td><td>{c.actual}</td><td>{pct(c.classical)}</td><td>{pct(c.quantum)}</td><td>{c.either_model_wrong?'Yes':'No'}</td></tr>)}</tbody></table></div><p className="muted">{lab.note}</p></>:<div className="empty"><GitMerge size={30}/><p>Train a calibrated classical + quantum-kernel experiment first.</p></div>}</section></>}
 {selected&&<section className="panel report-detail"><div className="panel-heading"><div><span className="tag">RESEARCH REPORT · {selected.id.slice(0,8)}</span><h3>{selected.dataset_name}</h3></div><button className="link" onClick={()=>setSelected(null)}>Close</button></div><div className="report-summary"><Shield size={24}/><div><h3>{selected.patient_view.summary}</h3><p>{selected.patient_view.next_step}</p></div></div><div className="model-probabilities"><div><small>Classical estimate</small><strong>{pct(selected.classical.probability)}</strong><span>{selected.classical.name}</span></div><div><small>Quantum estimate</small><strong>{pct(selected.quantum.probability)}</strong><span>{selected.quantum.name}</span></div></div><p className="muted">Probabilities refer to the dataset's positive label. Calibration does not establish clinical validity.</p>{selected.warnings.map(w=><div className="alert" key={w}>{w}</div>)}{selected.consensus&&<div className="consensus-detail"><h3>Research consensus</h3><p className="muted">Agreement: {selected.consensus.agreement?'Yes':'No'} · Gap: {pct(selected.consensus.probability_gap)} · Class set: [{selected.consensus.prediction_set.join(', ')}] · Uncertainty: {selected.consensus.uncertainty_level}</p>{selected.consensus.reasons.map(r=><p className="muted" key={r}>{r}</p>)}<p className="muted">Split-conformal class sets are not probability confidence intervals.</p></div>}{selected.explanation&&<div className="importance"><h3>Row-specific explanation · {selected.explanation.method}</h3>{selected.explanation.features.slice(0,8).map(f=><div key={f.feature}><span>{f.feature}</span><div className="track"><span style={{width:`${Math.abs(f.value)/Math.max(.001,...selected.explanation!.features.map(x=>Math.abs(x.value)))*100}%`}}/></div><b>{f.value.toFixed(3)}</b></div>)}</div>}
 <div className="report-downloads"><button className="secondary" onClick={()=>action(async()=>{const response=await fetch(`/api/reports/${selected.id}/pdf?audience=${user?.role==='patient'?'patient':'doctor'}&language=${user?.language_pref||'en'}`,{credentials:'same-origin'});if(!response.ok)throw Error('Unable to export report');const blob=await response.blob(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`qura-${selected.id.slice(0,8)}.pdf`;a.click();URL.revokeObjectURL(url);})}><Download size={15}/>Export report PDF</button></div>
 {user?.role!=='patient'&&<div className="review-form"><h3>Researcher review</h3><label>Review note<textarea rows={3} value={note} onChange={e=>setNote(e.target.value)} placeholder="Record an interpretation without changing the original model output"/></label><div className="form-row"><button className="secondary" disabled={busy||!note} onClick={()=>action(()=>review('note'))}>Save note</button><button className="primary" disabled={busy||!note} onClick={()=>action(()=>review('approve'))}><Check size={15}/>Approve report</button><select aria-label="Override label" value={override} onChange={e=>setOverride(Number(e.target.value))}><option value={0}>Override: label 0</option><option value={1}>Override: label 1</option></select><button className="secondary" disabled={busy||!note} onClick={()=>action(()=>review('override'))}>Record override</button></div></div>}{selected.reviews.map((r,i)=><div className="review-note" key={i}><strong>{r.doctor_name} · {r.action}</strong><p>{r.note}</p></div>)}</section>}
 </>;
}
