import React,{useMemo,useRef,useState} from 'react';
import {MapPin,ZoomIn,ZoomOut,RotateCcw} from 'lucide-react';
type Point={latitude:number;longitude:number};
/** Local interactive schematic: no tiles, external transmission or road-navigation claim. */
export default function EmergencyMap({pickup,location,hospital,route,candidates=[]}:{pickup:Point;location?:Point|null;hospital?:Point|null;route?:{polyline:number[][]}|null;candidates?:{id:string;name:string;latitude:number;longitude:number;eligible:boolean}[]}){
 const [zoom,setZoom]=useState(1),[offset,setOffset]=useState({x:0,y:0});const drag=useRef<{x:number;y:number;ox:number;oy:number}|null>(null);
 const bounds=useMemo(()=>{const points=[pickup,...(location?[location]:[]),...(hospital?[hospital]:[]),...candidates];const lats=points.map(p=>p.latitude),lons=points.map(p=>p.longitude);return {lat:Math.min(...lats)-.015,lon:Math.min(...lons)-.015,height:Math.max(.03,Math.max(...lats)-Math.min(...lats)+.03),width:Math.max(.03,Math.max(...lons)-Math.min(...lons)+.03)};},[pickup.latitude,pickup.longitude,location?.latitude,location?.longitude,hospital?.latitude,hospital?.longitude,candidates.map(c=>c.id).join(',')]);
 const project=(p:Point)=>({x:35+(p.longitude-bounds.lon)/bounds.width*530,y:280-(p.latitude-bounds.lat)/bounds.height*245});
 function marker(p:Point,label:string,color:string){const xy=project(p);return <g key={label}><circle cx={xy.x} cy={xy.y} r={8} fill={color} stroke="white" strokeWidth={3}/><text x={xy.x+12} y={xy.y+4} fill="#18333e" fontSize={11}>{label}</text></g>;}
 return <div className="emergency-map"><div className="map-toolbar"><span><MapPin size={16}/> Interactive schematic</span><div><button className="secondary" aria-label="Zoom in map" onClick={()=>setZoom(z=>Math.min(3,z+.25))}><ZoomIn size={16}/></button><button className="secondary" aria-label="Zoom out map" onClick={()=>setZoom(z=>Math.max(.75,z-.25))}><ZoomOut size={16}/></button><button className="secondary" aria-label="Reset map" onClick={()=>{setZoom(1);setOffset({x:0,y:0});}}><RotateCcw size={16}/></button></div></div><svg viewBox="0 0 600 315" role="img" aria-label="Schematic patient pickup, ambulance position and hospital route" onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);drag.current={x:e.clientX,y:e.clientY,ox:offset.x,oy:offset.y};}} onPointerMove={e=>{if(drag.current){const scale=600/e.currentTarget.getBoundingClientRect().width;setOffset({x:drag.current.ox+(e.clientX-drag.current.x)*scale,y:drag.current.oy+(e.clientY-drag.current.y)*scale});}}} onPointerUp={()=>{drag.current=null;}} onPointerCancel={()=>{drag.current=null;}}><defs><pattern id="emergency-grid" width="30" height="30" patternUnits="userSpaceOnUse"><path d="M 30 0 L 0 0 0 30" fill="none" stroke="#d5e5e8" strokeWidth={1}/></pattern></defs><rect width={600} height={315} fill="#edf6f6"/><rect width={600} height={315} fill="url(#emergency-grid)"/><g transform={`translate(${offset.x} ${offset.y}) translate(300 157) scale(${zoom}) translate(-300 -157)`}>{route&&<polyline points={route.polyline.map(p=>{const xy=project({latitude:p[0],longitude:p[1]});return `${xy.x},${xy.y}`;}).join(' ')} fill="none" stroke="#087f82" strokeWidth={4} strokeDasharray="8 5"/>}{!hospital&&location&&<line x1={project(location).x} y1={project(location).y} x2={project(pickup).x} y2={project(pickup).y} stroke="#087f82" strokeWidth={3} strokeDasharray="8 5"/>}{candidates.map((h,i)=>marker(h,`Hospital ${i+1}`,h.eligible?'#3383a6':'#adb4b8'))}{marker(pickup,'Pickup','#bf6c32')}{hospital&&marker(hospital,'Destination','#3383a6')}{location&&marker(location,'Ambulance','#087f82')}</g></svg><p>Drag to pan; use zoom controls. Straight lines are simulated links, not road directions. No real dispatch or road navigation is connected.</p></div>;
}
