import React from 'react';
import {tr} from './i18n';
type Summary={mean:number;std:number;ci95:[number,number];n:number};
/** Clearly separate development CV summaries from final test calibration diagnostics. */
export default function EvaluationEvidence({model}:{model:any}){
 if(!model?.cv)return null;
 const pct=(value:number)=>(value*100).toFixed(1)+'%';
 return <section className="panel"><div className="panel-heading"><div><h3>{tr('Repeated development cross-validation')}</h3><p>{model.config.cv_folds} × {model.config.cv_repeats} · {model.name}</p></div><span className="tag">{tr('FINAL TEST KEPT SEPARATE')}</span></div><div className="table-scroll"><table><thead><tr><th>{tr('Metric')}</th><th>{tr('Mean ± standard deviation')}</th><th>{tr('Descriptive 95% interval')}</th></tr></thead><tbody>{Object.entries(model.cv).map(([key,value])=>{const metric=value as Summary;return <tr key={key}><td>{tr({accuracy:'Accuracy',sensitivity:'Sensitivity',specificity:'Specificity',auc:'ROC–AUC'}[key]||key)}</td><td>{pct(metric.mean)} ± {pct(metric.std)}</td><td>{pct(metric.ci95[0])} – {pct(metric.ci95[1])}</td></tr>;})}</tbody></table></div><p className="muted">{tr('Overlapping folds are correlated. These intervals describe this run and are not independent-sample guarantees.')}</p><div className="form-row"><div><h3>{tr('Final-test Brier score')}</h3><strong>{model.brier.toFixed(4)}</strong><p className="muted">{tr('Lower is better; calibration is not clinical validation.')}</p></div><div><h3>{tr('Base training rows')}</h3><strong>{model.train_samples}</strong><p className="muted">{model.config.equal_budget?tr('Equal rows and reduced features across models'):tr('Classical and quantum budgets can differ')}</p></div></div><h3>{tr('Final-test reliability curve')}</h3><svg className="roc" viewBox="0 0 400 230" aria-label={tr('Final-test reliability curve')} role="img"><path d="M35,195 L375,20" stroke="#9fb5bd" strokeDasharray="5 5"/><path d={'M '+model.reliability.predicted.map((x:number,i:number)=>`${35+x*340},${195-model.reliability.observed[i]*175}`).join(' L ')} fill="none" stroke="#087f82" strokeWidth="3"/>{model.reliability.predicted.map((x:number,i:number)=><circle key={i} cx={35+x*340} cy={195-model.reliability.observed[i]*175} r={4} fill="#087f82"/>)}<text x="115" y="220">{tr('Predicted positive probability')}</text><text x="35" y="15">{tr('Observed positive fraction')}</text></svg>{model.seed_spread?.training_losses&&<p className="muted">{tr('VQC seed training-loss spread')}: {model.seed_spread.training_losses.map((v:number)=>v.toFixed(4)).join(', ')} · {tr('Standard deviation')}: {model.seed_spread.loss_std.toFixed(4)}</p>}</section>;
}
