import React,{useEffect,useRef,useState} from 'react';
import {Camera,Upload,Shield,Check,Trash2} from 'lucide-react';
import {request,useSession} from './session';
import {tr} from './i18n';
type Photo={id:string;patient_id:string;description:string;image_url:string;created_at:number;status:string;reviews:{doctor_name:string;note:string;created_at:number}[]};
/** Private photo submissions and human review, independent of research model inference. */
export default function PhotoPanel(){
 const {user}=useSession();const [photos,setPhotos]=useState<Photo[]>([]),[patients,setPatients]=useState<{id:string;name:string}[]>([]),[file,setFile]=useState<File|null>(null),[preview,setPreview]=useState(''),[description,setDescription]=useState(''),[consent,setConsent]=useState(false),[selected,setSelected]=useState<Photo|null>(null),[note,setNote]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');const input=useRef<HTMLInputElement>(null);
 const refresh=async()=>setPhotos(await request<Photo[]>('/photos'));
 useEffect(()=>{refresh().catch(e=>setError(e.message));request<{id:string;name:string}[]>('/patients').then(setPatients).catch(e=>setError(e.message));},[]);
 useEffect(()=>{if(!file){setPreview('');return;}const url=URL.createObjectURL(file);setPreview(url);return()=>URL.revokeObjectURL(url);},[file]);
 async function act(fn:()=>Promise<void>){setBusy(true);setError('');setMessage('');try{await fn();await refresh();}catch(e){setError(e instanceof Error?e.message:tr('Request failed'));}finally{setBusy(false);}}
 function choose(value:File|undefined){if(!value){setFile(null);return;}if(!['image/jpeg','image/png','image/webp'].includes(value.type)||value.size>10*1024*1024){setError(tr('Choose a JPEG, PNG or WebP photo up to 10 MB.'));setFile(null);return;}setError('');setFile(value);}
 async function submit(event:React.FormEvent){event.preventDefault();if(!file||!consent)return;await act(async()=>{const data=new FormData();data.append('file',file);data.append('description',description);data.append('photo_consent','true');const photo=await request<Photo>('/photos',data);setSelected(photo);setFile(null);if(input.current)input.current.value='';setDescription('');setConsent(false);setMessage(tr('Photo sent to your assigned doctor for review.'));});}
 return <><section className="panel photo-intro"><Camera size={26}/><div><h3>{user?.role==='patient'?tr('Share a photo for doctor review'):tr('Assigned patient photos')}</h3><p className="muted">{tr('Photos are for human review only. This app does not detect infections or diagnose images.')}</p><p className="muted">{tr('Only you, your assigned doctors and authorized administrators can access these photos.')}</p><p className="muted">{tr('Use anonymized or synthetic photos only. Crop out faces, names and identifying details. Photos are not sent to the AI assistant.')}</p></div></section>{error&&<div className="alert" role="alert">{error}</div>}{message&&<div className="alert" role="status">{message}</div>}
 {user?.role==='patient'&&<form className="panel photo-upload" onSubmit={submit}><div className="panel-heading"><h3>{tr('Upload a photo')}</h3><span className="tag"><Shield size={12}/>{tr('PRIVATE · AUTHORIZED ACCESS')}</span></div><label className="photo-file-label">{tr('Photo file')}<input ref={input} type="file" aria-label={tr('Photo file')} aria-describedby="photo-file-help" accept="image/jpeg,image/png,image/webp" onChange={e=>choose(e.target.files?.[0])}/><small id="photo-file-help">{tr('JPEG, PNG or WebP · Up to 10 MB · No automatic diagnosis')}</small></label>{preview&&<img className="photo-preview" src={preview} alt={tr('Selected photo preview')}/>}<label>{tr('Optional description')}<textarea value={description} onChange={e=>setDescription(e.target.value)} maxLength={2000} rows={3} placeholder={tr('Describe the photo without including identifying details.')}/></label><label className="consent-toggle"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>{tr('I agree to store this photo and share it with my assigned doctor for review.')}</label><p className="muted">{tr('Research consent must be enabled, and an administrator must assign your doctor before uploading.')}</p><button className="primary" disabled={!file||!consent||busy}><Upload size={16}/>{busy?tr('Please wait…'):tr('Send photo for review')}</button></form>}
 <section className="panel"><div className="panel-heading"><h3>{user?.role==='patient'?tr('My photo submissions'):tr('Photo review queue')}</h3><span className="tag">{photos.length}</span></div>{!photos.length&&<div className="empty"><Camera size={28}/><p>{tr('No photo submissions yet.')}</p></div>}<div className="photo-list">{photos.map(photo=><button className="photo-card" key={photo.id} onClick={()=>{setSelected(photo);setNote('');}}><img loading="lazy" src={photo.image_url} alt={tr('Submitted photo')}/><span><strong>{user?.role==='patient'?tr('Photo submission'):patients.find(p=>p.id===photo.patient_id)?.name||tr('Assigned patient')}</strong><small>{new Date(photo.created_at*1000).toLocaleString()}</small><span className={'status '+photo.status}>{photo.status==='reviewed'?tr('Reviewed'):tr('Awaiting doctor review')}</span></span></button>)}</div></section>
 {selected&&<section className="panel photo-detail"><div className="panel-heading"><h3>{tr('Photo submission')}</h3><button className="link" onClick={()=>setSelected(null)}>{tr('Close')}</button></div><img className="photo-full" src={selected.image_url} alt={tr('Submitted photo for doctor review')}/><p>{selected.description}</p><p className="muted">{selected.status==='reviewed'?tr('Reviewed'):tr('Awaiting doctor review')}</p>{selected.reviews.map((review,i)=><div className="review-note" key={i}><strong>{review.doctor_name} · {new Date(review.created_at*1000).toLocaleString()}</strong><p>{review.note}</p></div>)}{user?.role==='doctor'&&<div className="review-form"><label>{tr('Photo review note')}<textarea maxLength={2000} rows={3} value={note} onChange={e=>setNote(e.target.value)}/></label><button className="primary" disabled={busy||!note.trim()} onClick={()=>act(async()=>{setSelected(await request<Photo>(`/photos/${selected.id}/review`,{note}));setNote('');})}><Check size={16}/>{tr('Send review to patient')}</button></div>}{user?.role==='patient'&&<button className="secondary" disabled={busy} onClick={()=>{if(window.confirm(tr('Delete this photo and its review notes? This cannot be undone.')))void act(async()=>{await request(`/photos/${selected.id}`,undefined,'DELETE');setSelected(null);setMessage(tr('Photo deleted.'));});}}><Trash2 size={15}/>{tr('Delete photo')}</button>}</section>}
 </>;
}
