import React,{useEffect,useState} from 'react';
import {Ambulance,Building2,UserPlus} from 'lucide-react';
import {request,useSession,User} from './session';

type Resources={ambulances:any[];hospitals:any[];warning:string};
export default function ResourcePanel(){
 const {user}=useSession();const [data,setData]=useState<Resources>({ambulances:[],hospitals:[],warning:''}),[users,setUsers]=useState<User[]>([]),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const refresh=async()=>{setData(await request('/emergency/resources'));if(user?.role==='admin')setUsers(await request<User[]>('/admin/users'));};
 useEffect(()=>{refresh().catch(e=>setError(e.message));const timer=setInterval(()=>refresh().catch(()=>{}),5000);return()=>clearInterval(timer);},[]);
 const mutate=async(path:string,payload:unknown,method='POST')=>{setError('');setMessage('');setBusy(true);try{await request(path,payload,method);await refresh();setMessage('Resource configuration saved.');return true;}catch(e){setError(e instanceof Error?e.message:'Unable to save');return false;}finally{setBusy(false);}};
 return <><section className="panel"><div className="panel-heading"><div><h3><Building2 size={18}/> Fleet and receiving hospitals</h3><p>Capacity is reported manually and refreshed every five seconds. Reserved beds are excluded from available counts.</p></div></div><div className="simulation-banner">{data.warning||'Synthetic demonstration resources only. No live hospital system is connected.'}</div>{error&&<div className="alert" role="alert">{error}</div>}{message&&<div className="alert" role="status">{message}</div>}{data.ambulances.length>0&&<div className="resource-cards">{data.ambulances.map(unit=><article className="care-summary" key={unit.id}><h3><Ambulance size={18}/>{unit.name}</h3><p>Status: <strong>{unit.status}</strong></p><p className="muted">Equipment: {JSON.parse(unit.equipment).join(', ')}</p>{user?.role==='admin'&&['available','unavailable'].includes(unit.status)&&<button className="secondary" disabled={busy} onClick={()=>void mutate(`/emergency/ambulances/${unit.id}/availability`,{status:unit.status==='available'?'unavailable':'available'},'PUT')}>{unit.status==='available'?'Mark unit unavailable':'Make unit available'}</button>}</article>)}</div>}<div className="resource-cards">{data.hospitals.map(hospital=><HospitalCapacity key={hospital.id} hospital={hospital} save={(payload)=>mutate(`/emergency/hospitals/${hospital.id}/capacity`,payload,'PUT')} editable={user?.role==='hospital'||user?.role==='admin'}/>)}</div>{!data.hospitals.length&&<div className="empty">No hospital resource is linked to this account yet. Ask administration to register it.</div>}</section>{user?.role==='admin'&&<><ServiceAccountForm save={payload=>mutate('/admin/service-accounts',payload)}/><FleetForm users={users} registered={data.ambulances.map(u=>u.driver_id)} save={payload=>mutate('/emergency/ambulances',payload)}/><HospitalForm users={users} registered={data.hospitals.map(h=>h.user_id)} save={payload=>mutate('/emergency/hospitals',payload)}/></>}</>;
}

function HospitalCapacity({hospital,save,editable}:{hospital:any;save:(p:unknown)=>Promise<boolean>;editable:boolean}){
 const [beds,setBeds]=useState(hospital.beds),[icu,setIcu]=useState(hospital.icu_beds),[accepting,setAccepting]=useState(!!hospital.accepting),[traffic,setTraffic]=useState(hospital.traffic_factor),[busy,setBusy]=useState(false);
 useEffect(()=>{setBeds(hospital.beds);setIcu(hospital.icu_beds);setAccepting(!!hospital.accepting);setTraffic(hospital.traffic_factor);},[hospital.updated_at,hospital.beds,hospital.icu_beds,hospital.accepting,hospital.traffic_factor]);
 return <form className="care-summary hospital-capacity" onSubmit={async e=>{e.preventDefault();setBusy(true);await save({beds,icu_beds:icu,accepting,traffic_factor:traffic});setBusy(false);}}><h3><Building2 size={18}/>{hospital.name}</h3><p className="muted">{hospital.source.replace(/_/g,' ')} · Last reported {new Date(hospital.updated_at*1000).toLocaleString()}</p>{Date.now()/1000-hospital.updated_at>1800&&<div className="alert">Capacity is stale. Refresh the report before accepting a case.</div>}<fieldset disabled={!editable||busy}><div className="care-grid"><label>Reported free general beds<input type="number" required min={0} max={10000} value={beds} onChange={e=>setBeds(Number(e.target.value))}/></label><label>Reported free ICU beds<input type="number" required min={0} max={10000} value={icu} onChange={e=>setIcu(Number(e.target.value))}/></label><label>Simulated traffic multiplier<input type="number" required min={1} max={4} step={.1} value={traffic} onChange={e=>setTraffic(Number(e.target.value))}/></label></div><label className="consent-toggle"><input type="checkbox" checked={accepting} onChange={e=>setAccepting(e.target.checked)}/>Accepting new referral requests</label>{editable&&<button className="primary">Update reported capacity</button>}</fieldset><p className="muted">Reported availability does not accept a case. Confirm each referral in Emergency cases; withdrawing availability flags accepted cases for reconfirmation.</p></form>;
}

function ServiceAccountForm({save}:{save:(payload:unknown)=>Promise<boolean>}){
 const [name,setName]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[role,setRole]=useState('driver'),[busy,setBusy]=useState(false);
 return <form className="panel form-stack" onSubmit={async e=>{e.preventDefault();setBusy(true);if(await save({name,email,password,role})){setName('');setEmail('');setPassword('');}setBusy(false);}}><h3><UserPlus size={18}/> Provision a service account</h3><p className="muted">Driver and hospital accounts are created by administration, not public signup. Share credentials through your trusted process outside this prototype.</p><div className="care-grid"><label>Service account name<input required minLength={2} maxLength={80} value={name} onChange={e=>setName(e.target.value)}/></label><label>Service account email<input type="email" required maxLength={200} value={email} onChange={e=>setEmail(e.target.value)}/></label></div><div className="care-grid"><label>Service account role<select aria-label="Service account role" value={role} onChange={e=>setRole(e.target.value)}><option value="driver">Ambulance driver</option><option value="hospital">Receiving hospital</option></select></label><label>Initial account password<input type="password" autoComplete="new-password" required minLength={12} maxLength={128} value={password} onChange={e=>setPassword(e.target.value)}/></label></div><p className="muted">At least 12 characters with uppercase, lowercase, a number and a symbol. Passwords are hashed server-side and never returned in account listings.</p><button className="primary" disabled={busy}>Create service account</button></form>;
}

function FleetForm({users,registered,save}:{users:User[];registered:string[];save:(payload:unknown)=>Promise<boolean>}){
 const [driver,setDriver]=useState(''),[name,setName]=useState(''),[lat,setLat]=useState('13.04'),[lon,setLon]=useState('80.22'),[busy,setBusy]=useState(false);
 return <form className="panel form-stack" onSubmit={async e=>{e.preventDefault();setBusy(true);if(await save({driver_id:driver,name,latitude:Number(lat),longitude:Number(lon),equipment:['general','cardiac','trauma']})){setName('');setDriver('');}setBusy(false);}}><h3>Register an ambulance unit</h3><div className="care-grid"><label>Unit name<input required minLength={2} maxLength={80} value={name} onChange={e=>setName(e.target.value)}/></label><label>Unit driver<select aria-label="Unit driver" required value={driver} onChange={e=>setDriver(e.target.value)}><option value="">Select unlinked driver</option>{users.filter(u=>u.role==='driver'&&u.approved&&!registered.includes(u.id)).map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></label><label>Unit initial latitude<input type="number" required min={-90} max={90} step="any" value={lat} onChange={e=>setLat(e.target.value)}/></label><label>Unit initial longitude<input type="number" required min={-180} max={180} step="any" value={lon} onChange={e=>setLon(e.target.value)}/></label></div><p className="muted">The demo unit reports general, cardiac and trauma transport equipment. Verify actual equipment and staffing before any real deployment.</p><button className="primary" disabled={busy||!driver}>Register ambulance</button></form>;
}

function HospitalForm({users,registered,save}:{users:User[];registered:string[];save:(payload:unknown)=>Promise<boolean>}){
 const [account,setAccount]=useState(''),[name,setName]=useState(''),[lat,setLat]=useState('13.06'),[lon,setLon]=useState('80.25'),[beds,setBeds]=useState(5),[icu,setIcu]=useState(2),[busy,setBusy]=useState(false);
 return <form className="panel form-stack" onSubmit={async e=>{e.preventDefault();setBusy(true);if(await save({user_id:account,name,latitude:Number(lat),longitude:Number(lon),beds,icu_beds:icu,capabilities:['general','cardiac','trauma']})){setName('');setAccount('');}setBusy(false);}}><h3>Register a receiving hospital</h3><div className="care-grid"><label>Hospital name<input required minLength={2} maxLength={120} value={name} onChange={e=>setName(e.target.value)}/></label><label>Hospital account<select aria-label="Hospital account" required value={account} onChange={e=>setAccount(e.target.value)}><option value="">Select unlinked hospital account</option>{users.filter(u=>u.role==='hospital'&&u.approved&&!registered.includes(u.id)).map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></label><label>Hospital latitude<input required type="number" step="any" min={-90} max={90} value={lat} onChange={e=>setLat(e.target.value)}/></label><label>Hospital longitude<input required type="number" step="any" min={-180} max={180} value={lon} onChange={e=>setLon(e.target.value)}/></label><label>Initial general beds<input required type="number" min={0} max={10000} value={beds} onChange={e=>setBeds(Number(e.target.value))}/></label><label>Initial ICU beds<input required type="number" min={0} max={10000} value={icu} onChange={e=>setIcu(Number(e.target.value))}/></label></div><p className="muted">Demo capabilities: general, cardiac and trauma. This is a manually reported resource, not a verified hospital-information-system connection.</p><button className="primary" disabled={busy||!account}>Register receiving hospital</button></form>;
}
