import {tr} from './i18n';
import React,{useEffect,useState} from 'react';
import {FlaskConical,ArrowRight} from 'lucide-react';
import {request} from './session';
import {Report,Schema} from './ClinicalPanel';
/** Debounced model-behavior exploration; original reports are never overwritten. */
export default function WhatIfPanel(){
 const [reports,setReports]=useState<Report[]>([]),[schemas,setSchemas]=useState<Schema[]>([]),[id,setId]=useState(''),[changes,setChanges]=useState<Record<string,number>>({}),[result,setResult]=useState<any>(null),[counter,setCounter]=useState<any>(null),[error,setError]=useState('');
 const report=reports.find(r=>r.id===id),schema=schemas.find(s=>s.id===report?.dataset_id);
 useEffect(()=>{request<Report[]>('/reports').then(r=>{setReports(r);setId(r[0]?.id||'');}).catch(e=>setError(e.message));request<Schema[]>('/clinical/datasets').then(setSchemas).catch(e=>setError(e.message));},[]);
 useEffect(()=>{if(!id)return;let cancelled=false;const timer=setTimeout(()=>request('/what-if',{report_id:id,changes}).then(r=>{if(!cancelled){setResult(r);setError('');}}).catch(e=>{if(!cancelled)setError(e.message);}),450);return()=>{cancelled=true;clearTimeout(timer);};},[id,changes]);
 return <><section className="panel"><div className="panel-heading"><div><h3>{tr("What happens when the inputs change?")}</h3><p>{tr("Explore a model. Do not use these values as health targets.")}</p></div><FlaskConical size={25}/></div>{error&&<div className="alert" role="alert">{error}</div>}<label>{tr("Research report")}<select aria-label={tr("Research report")} value={id} onChange={e=>{setId(e.target.value);setChanges({});setCounter(null);setResult(null);setError('');}}>{reports.map(r=><option value={r.id} key={r.id}>{r.dataset_name} · {r.id.slice(0,8)}</option>)}</select></label>{!reports.length&&<div className="empty">{tr("Create a research report first to explore its model behavior.")}</div>}<div className="whatif-sliders">{schema?.features.filter(f=>f.numeric&&f.max!==f.min).slice(0,5).map(f=><label key={f.name}><span>{f.name}<b>{(changes[f.name]??Number(report?.sample[f.name]||0)).toFixed(2)} {f.unit}</b></span><input type="range" min={f.min??0} max={f.max??1} step={((f.max??1)-(f.min??0))/100} value={changes[f.name]??Number(report?.sample[f.name]||0)} onChange={e=>setChanges(v=>({...v,[f.name]:Number(e.target.value)}))}/><small>{tr("Observed benchmark range. This feature may not be changeable in practice.")}</small></label>)}</div>{result&&<div className="model-probabilities">{['classical','quantum'].map(branch=><div key={branch}><small>{branch}{tr("model estimate")}</small><strong>{(result.probabilities[branch]*100).toFixed(1)}%</strong><span>{tr("Original:")}{(result.original[branch]*100).toFixed(1)}%</span><div className="track"><span style={{width:`${result.probabilities[branch]*100}%`}}/></div></div>)}</div>}<p className="muted">{tr("Model behavior only. Changes do not represent medical recommendations, safe targets, or proof that an outcome would change.")}</p><button className="secondary" disabled={!id} onClick={async()=>{try{setCounter(await request('/what-if/counterfactual',{report_id:id,changes:{}}));}catch(e){setError(e instanceof Error?e.message:tr("Request failed"));}}}>{tr("Explore bounded counterfactuals")}<ArrowRight size={15}/></button>{counter&&<div className="counterfactuals"><p className="muted">{counter.note}</p>{counter.candidates.map((c:any,i:number)=><div className="review-note" key={i}><strong>{c.feature}</strong><p>{tr("From")}{c.original}{tr("to")}{c.value.toFixed(3)}{tr("· Model estimate")}{(c.probability*100).toFixed(1)}%</p></div>)}</div>}</section></>;
}
