import React, { useState } from 'react';
import { useNavigation } from '../../context/NavigationContext';
import { Map, MapPin, Sparkles, ArrowRight, ArrowUpRight, Search, Users, Bus, BedDouble, GraduationCap, CalendarDays, QrCode, Compass, Building2, BookOpen } from 'lucide-react';
import { TabKey } from '../common/NavigationSidebar';
import { BUILDINGS, CAMPUS_EVENTS } from '../../data/mockData';
export const HomeModule: React.FC<{ onSelectTab: (tab: TabKey) => void }> = ({ onSelectTab }) => {
const { setTargetDestination, setQRModalOpen } = useNavigation();
const [query, setQuery] = useState('');
const results = query.trim() ? BUILDINGS.filter(b => `${b.name} ${b.facilities.join(' ')} ${b.departments.join(' ')}`.toLowerCase().includes(query.toLowerCase())).slice(0, 5) : [];
const navigate = (id: string) => { setTargetDestination(id); onSelectTab('navigation'); };
const services: { tab: TabKey; title: string; subtitle: string; icon: React.ElementType }[] = [
{ tab: 'faculty', title: 'Find faculty', subtitle: 'People & departments', icon: Users }, { tab: 'bus', title: 'Campus transport', subtitle: 'Routes & schedules', icon: Bus }, { tab: 'hostel', title: 'Hostel & dining', subtitle: 'Your home on campus', icon: BedDouble }, { tab: 'admissions', title: 'Admissions', subtitle: 'Plan your next chapter', icon: GraduationCap }];
return <div className="home-page">
<div className="page-intro"><div><p className="eyebrow">R.M.K. ENGINEERING COLLEGE</p><h1>A little guidance. Endless possibilities.</h1><p>Find your way, meet your people, and make yourself at home.</p></div><button className="subtle-button" onClick={() => setQRModalOpen(true)}><QrCode size={16} /> Take campus with you</button></div>
<section className="campus-hero"><img src="/assets/rmk_photo_3.png" alt="College library and student life" /><div className="hero-shade" /><div className="hero-copy"><span className="hero-tag"><Compass size={14} /> YOUR JOURNEY STARTS HERE</span><h2>A campus of possibilities.<br /><em>Find your way.</em></h2><p>From your first visit to your everyday destination,<br className="desktop-break" /> your campus companion is right here.</p><button className="primary-button" onClick={() => onSelectTab('navigation')}>Explore campus map <ArrowUpRight size={18} /></button></div><div className="hero-caption"><MapPin size={15} /><span>R.M.K. Engineering College<small>Kavaraipettai · Tamil Nadu</small></span></div></section>
<div className="home-columns"><div className="home-main"><div className="search-area"><Search size={20} /><input aria-label="Search campus destinations" placeholder="Where would you like to go? Search campus…" value={query} onChange={e => setQuery(e.target.value)} /><kbd>Explore</kbd>{query.trim() && <div className="search-results">{results.length ? results.map(b => <button key={b.id} onClick={() => navigate(b.id)}><MapPin size={17} /><span>{b.shortName || b.name}<small>{b.name}</small></span><ArrowRight size={16} /></button>) : <p>No destinations found. Try “library”, “office” or “hostel”.</p>}</div>}</div>
<div className="section-heading"><h2>Everything you need, right here</h2><span>CAMPUS ESSENTIALS</span></div><div className="service-grid">{services.map(({ tab, title, subtitle, icon: Icon }) => <button className="service-card" key={tab} onClick={() => onSelectTab(tab)}><span className={`service-icon ${tab}`}><Icon size={22} /></span><ArrowUpRight className="service-arrow" size={17} /><strong>{title}</strong><p>{subtitle}</p></button>)}</div>
<div className="section-heading"><h2>Popular destinations</h2><button onClick={() => onSelectTab('navigation')}>View map <ArrowRight size={14} /></button></div><div className="destination-grid">{[{ id: 'b-sn', name: 'Central library', detail: 'Read. Research. Discover.', icon: BookOpen }, { id: 'b-rj', name: 'Administration', detail: 'A helping hand for your visit', icon: Building2 }, { id: 'b-aud', name: 'Auditorium', detail: 'Where the campus comes together', icon: Map }].map(({ id, name, detail, icon: Icon }) => <button key={id} onClick={() => navigate(id)}><Icon size={19} /><span><strong>{name}</strong><small>{detail}</small></span><ArrowRight size={16} /></button>)}</div>
<div className="welcome-strip"><GraduationCap size={27} /><div><strong>Visiting for the first time?</strong><p>Everything students and parents need for a smooth campus visit.</p></div><button onClick={() => onSelectTab('guide')}>Open visitor guide <ArrowUpRight size={16} /></button></div></div>
<aside className="home-rail"><section className="assistant-card"><div className="assistant-icon"><Sparkles size={24} /></div><span className="eyebrow">MEET YOUR CAMPUS COMPANION</span><h2>A question?<br />Start a conversation.</h2><p>Get help with campus locations, departments and everyday questions.</p>{['Where is the library?', 'How do I find the admissions office?'].map(prompt => <button className="prompt-button" key={prompt} onClick={() => { sessionStorage.setItem('campus-prompt', prompt); onSelectTab('ai'); }}>{prompt}<ArrowUpRight size={15} /></button>)}<button className="assistant-cta" onClick={() => onSelectTab('ai')}>Ask campus assistant <ArrowRight size={17} /></button></section>
<section className="events-preview"><div className="section-heading"><h2>On the calendar</h2><CalendarDays size={18} /></div>{CAMPUS_EVENTS.filter(e => new Date(e.date).getTime() >= new Date().setHours(0, 0, 0, 0)).slice(0, 2).map(event => <button key={event.id} onClick={() => onSelectTab('events')}><span className="event-date"><small>{new Date(event.date).toLocaleDateString('en', { month: 'short' })}</small>{new Date(event.date).getDate()}</span><span><strong>{event.title}</strong><small>{event.category}</small></span></button>)}<button className="all-events" onClick={() => onSelectTab('events')}>Explore all events <ArrowRight size={14} /></button></section></aside></div>
<footer className="product-footer"><span>R.M.K. Engineering College · Campus companion</span><button onClick={() => onSelectTab('about')}>Discover our college <ArrowUpRight size={13} /></button></footer></div>;
};
