import React, { useState } from 'react';
import { BUILDINGS, FACULTY_LIST, CAMPUS_EVENTS, BUS_ROUTES, HOSTELS, ADMISSION_COURSES } from '../../data/mockData';
import { KNOWLEDGE_CORPUS } from '../../services/ragEngine';
import { Database, Download, Search, CheckCircle2 } from 'lucide-react';
const datasets = { buildings: BUILDINGS, faculty: FACULTY_LIST, events: CAMPUS_EVENTS, transport: BUS_ROUTES, hostels: HOSTELS, admissions: ADMISSION_COURSES, knowledge: KNOWLEDGE_CORPUS };
type Dataset = keyof typeof datasets;
export const AdminDashboard: React.FC = () => {
const [active, setActive] = useState<Dataset>('buildings');
const [query, setQuery] = useState('');
const [notice, setNotice] = useState('');
const exportData = () => { const url = URL.createObjectURL(new Blob([JSON.stringify(datasets, null, 2)], { type:'application/json' })); const link = document.createElement('a'); link.href=url; link.download='rmk-campus-data.json'; link.click(); setTimeout(() => URL.revokeObjectURL(url),1000); setNotice('Campus data exported for review.'); };
const records = datasets[active] as unknown as Record<string, unknown>[];
const filtered = records.filter(record => JSON.stringify(record).toLowerCase().includes(query.toLowerCase()));
return <div className="space-y-6"><section className="glass-panel p-6 rounded-3xl"><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="flex items-center gap-2 text-lg font-semibold"><Database size={21} />Campus data review</h2><p className="text-xs text-slate-400 mt-2">Review the information included in this presentation and export it for the college team.</p></div><button className="primary-button" onClick={exportData}><Download size={16} />Export campus data</button></div><p className="text-xs text-amber-200 mt-5">These are local sample records. This review screen does not provide secure administrative access or update college systems.</p>{notice && <p className="flex gap-2 text-xs text-emerald-200 mt-3" role="status"><CheckCircle2 size={15} />{notice}</p>}</section><div className="flex flex-wrap gap-2">{(Object.keys(datasets) as Dataset[]).map(key => <button key={key} onClick={() => { setActive(key); setQuery(''); }} className={`px-4 py-2 rounded-xl border text-xs capitalize ${active === key ? 'bg-emerald-900 border-emerald-600 text-white' : 'border-slate-700 text-slate-400'}`}>{key} ({datasets[key].length})</button>)}</div><label className="search-area"><Search size={18} /><input aria-label="Search campus records" value={query} onChange={e => setQuery(e.target.value)} placeholder={`Search ${active} records…`} /></label><p className="text-xs text-slate-400">{filtered.length} records</p><div className="grid grid-cols-1 md:grid-cols-2 gap-4">{filtered.map(record => <article className="glass-panel rounded-3xl p-5" key={String(record.id)}><h3 className="font-semibold text-sm">{String(record.name || record.title || record.routeName || record.branch)}</h3><dl className="mt-3 space-y-2">{Object.entries(record).filter(([key,value]) => key !== 'id' && typeof value !== 'object' && !['name','title','routeName','branch','photoUrl'].includes(key)).map(([key,value]) => <div key={key} className="text-xs"><dt className="text-slate-400 capitalize">{key.replace(/([A-Z])/g,' $1')}</dt><dd className="text-slate-200 break-words">{String(value)}</dd></div>)}</dl></article>)}</div>{filtered.length === 0 && <p className="glass-panel p-8 rounded-xl text-sm text-slate-400">No matching records. Try a different search.</p>}</div>;
};
