import React, { useEffect, useRef } from 'react';
import { useNavigation } from '../../context/NavigationContext';
import { BUILDINGS, MAP_NODES } from '../../data/mockData';
import { QrCode, MapPin, Maximize2, ArrowLeftRight } from 'lucide-react';
const MAP_PLACES: Record<string, string> = { 'b-gate':'MGT', 'b-temple':'TMP', 'b-rj':'RJB', 'b-new':'NWB', 'b-sn':'SNB', 'b-sv':'SVB', 'b-lk':'LKB', 'b-ss':'SSB', 'b-pv':'PVB', 'b-vr':'VRB', 'b-h-gents':'BH1', 'b-h-ladies':'GH4', 'b-mess-boys':'MES', 'b-mess-girls':'MES', 'b-sports':'PLG', 'b-parking':'PRK', 'b-stp':'STP' };
export const CampusMap2D: React.FC = () => {
const { selectedBuilding, startNodeId, setStartLocation, targetNodeId, setTargetDestination, setQRModalOpen, clearRoute, activeRoute } = useNavigation();
const startBuildingId = MAP_NODES.find(n => n.id === startNodeId)?.buildingId || 'b-gate';
const frame = useRef<HTMLIFrameElement>(null); const container = useRef<HTMLDivElement>(null);
const sendDestination = () => { frame.current?.contentWindow?.postMessage({ type:'campus-destination', from:MAP_PLACES[startBuildingId] || null, to:targetNodeId ? MAP_PLACES[selectedBuilding.id] || null : null }, window.location.origin); };
useEffect(sendDestination, [selectedBuilding.id, targetNodeId, startBuildingId]);
useEffect(() => { const listener = (event: MessageEvent) => { if (event.origin !== window.location.origin || event.source !== frame.current?.contentWindow || event.data?.type !== 'campus-map-selection') return; const fromId = Object.keys(MAP_PLACES).find(key => MAP_PLACES[key] === event.data.from); if (fromId) setStartLocation(fromId); const id = Object.keys(MAP_PLACES).find(key => MAP_PLACES[key] === event.data.to); if (event.data.to === null) clearRoute(); else if (id) setTargetDestination(id); }; window.addEventListener('message', listener); return () => window.removeEventListener('message', listener); }, [setTargetDestination, clearRoute, setStartLocation]);
return <div className="space-y-4"><div className="map-toolbar"><MapPin size={18} className="text-emerald-300" /><label className="map-destination-label">Starting point<select aria-label="Choose starting location" value={startBuildingId} onChange={e => setStartLocation(e.target.value)} className="map-destination-select">{BUILDINGS.map(b => <option key={b.id} value={b.id}>{b.shortName || b.name}</option>)}</select></label><button className="route-swap" aria-label="Swap start and destination" disabled={!targetNodeId} onClick={() => { const previousStart = startBuildingId; setStartLocation(selectedBuilding.id); setTargetDestination(previousStart); }}><ArrowLeftRight size={19} /></button><label className="map-destination-label">Destination <select aria-label="Choose campus destination" value={targetNodeId ? selectedBuilding.id : ''} onChange={e => e.target.value ? setTargetDestination(e.target.value) : clearRoute()} className="map-destination-select"><option value="">Choose a destination</option>{BUILDINGS.map(b => <option key={b.id} value={b.id}>{b.shortName || b.name}</option>)}</select></label><button className="subtle-button" onClick={() => setQRModalOpen(true)}><QrCode size={16} />Send to phone</button><button className="subtle-button" onClick={() => container.current?.requestFullscreen?.()}><Maximize2 size={16} />Expand map</button>{targetNodeId && <button className="subtle-button" onClick={clearRoute}>Clear route</button>}</div>{!MAP_PLACES[startBuildingId] && <p role="status" className="map-error">This starting location is not plotted on the illustrated map. Choose a plotted building for visual directions, or ask campus staff for assistance.</p>}{targetNodeId && !activeRoute && <p role="status" className="map-error">No route is available with your current settings. Choose another starting point or destination, or ask campus staff for directions.</p>}{targetNodeId && !MAP_PLACES[selectedBuilding.id] && <section className="map-location-summary"><MapPin size={22} /><div><h2>{selectedBuilding.name}</h2><p>{selectedBuilding.description}</p><small>This destination is not plotted on the illustrated map. Ask at the main gate for directions.</small></div></section>}<div ref={container} className="map-container"><button className="map-exit-fullscreen" onClick={() => document.exitFullscreen?.()} aria-label="Exit expanded map">Close expanded map ×</button><iframe ref={frame} src="/rmk_campus_router.html" onLoad={sendDestination} title="RMK Campus Navigation & Wayfinding Router" className="w-full h-[780px] border-0" /><p className="map-footnote">Illustrated campus guide. Walking distances are estimates. Confirm accessible paths with campus staff before travelling.</p></div></div>;
};
