"""Maintain all catalog keys; localized core copy and explicit English technical fallback."""
import json
from pathlib import Path

root=Path(__file__).resolve().parents[1]
en=json.loads((root/'src/research/locales/en.json').read_text(encoding='utf-8'))
keys='Overview|Dashboard|Datasets|Preprocessing|Model training|Quantum circuit|Evaluation|Explainability|Predictions|Experiments|Documentation|Research tools|My patients|My reports|Review queue|Consensus Lab|What-if lab|Users & assignments|Audit log|Measurements|Assistant|Consent|Name|Email|Role|Approval|Accuracy|Sensitivity|Specificity|Model|Probability|Language|Active|Submitted|Reviewed|Yes|No|Select|Close|Undefined|Research overview|Dataset samples|Input features|Trained models|Best ROC–AUC|Patient Portal|Doctor Portal|Full name|Email address|Password|Create account|Sign in securely|Sign out|Create your account|Welcome back.|New experiment|Doctor|Patient|Save assignment|Approve doctor|Your consent matters.|Research prototype|Request failed|Please wait…|Export report PDF|Load benchmark sample|Run prediction|Select model|Research dataset|Research report|Open workspace|Create research report|Fill synthetic demo|Review note|Save note|Approve report|Research consensus|Agreement|Disagreement|Explain my result|What does confidence mean?|What should I ask my doctor?|Send message|Delete chat history|Voice input|Read aloud|AI assistant, not a doctor'.split('|')
translations={
'ta':'கண்ணோட்டம்|முகப்பு|தரவுத்தொகுப்புகள்|முன்செயலாக்கம்|மாதிரி பயிற்சி|குவாண்டம் சுற்று|மதிப்பீடு|விளக்கம்|கணிப்புகள்|சோதனைகள்|ஆவணங்கள்|ஆய்வுக் கருவிகள்|எனது பங்கேற்பாளர்கள்|எனது அறிக்கைகள்|மதிப்பாய்வு வரிசை|ஒப்புமை ஆய்வகம்|மாற்ற ஆய்வகம்|பயனர்கள் மற்றும் ஒதுக்கீடுகள்|தணிக்கை பதிவு|அளவீடுகள்|உதவியாளர்|ஒப்புதல்|பெயர்|மின்னஞ்சல்|பங்கு|அனுமதி|துல்லியம்|உணர்திறன்|தனித்திறன்|மாதிரி|நிகழ்தகவு|மொழி|செயலில்|சமர்ப்பிக்கப்பட்டது|மதிப்பாய்வு செய்யப்பட்டது|ஆம்|இல்லை|தேர்வு|மூடு|வரையறுக்கப்படவில்லை|ஆய்வுக் கண்ணோட்டம்|தரவு மாதிரிகள்|உள்ளீட்டு அம்சங்கள்|பயிற்சி பெற்ற மாதிரிகள்|சிறந்த ROC–AUC|பங்கேற்பாளர் தளம்|மருத்துவர் தளம்|முழுப் பெயர்|மின்னஞ்சல் முகவரி|கடவுச்சொல்|கணக்கு உருவாக்கு|பாதுகாப்பாக உள்நுழை|வெளியேறு|உங்கள் கணக்கை உருவாக்கவும்|மீண்டும் வருக.|புதிய சோதனை|மருத்துவர்|பங்கேற்பாளர்|ஒதுக்கீட்டை சேமி|மருத்துவரை அனுமதி|உங்கள் ஒப்புதல் முக்கியம்.|ஆய்வு மாதிரி|கோரிக்கை தோல்வி|காத்திருக்கவும்…|PDF அறிக்கையைப் பதிவிறக்கு|ஆய்வு மாதிரியை ஏற்று|கணிப்பை இயக்கு|மாதிரியை தேர்ந்தெடு|ஆய்வு தரவுத்தொகுப்பு|ஆய்வு அறிக்கை|பணியிடத்தை திற|ஆய்வு அறிக்கை உருவாக்கு|செயற்கை எடுத்துக்காட்டை நிரப்பு|மதிப்பாய்வு குறிப்பு|குறிப்பை சேமி|அறிக்கையை அனுமதி|ஆய்வு ஒப்புமை|ஒத்துப்போதல்|வேறுபாடு|எனது முடிவை விளக்கு|நம்பிக்கை என்றால் என்ன?|மருத்துவரிடம் என்ன கேட்கலாம்?|செய்தி அனுப்பு|உரையாடலை நீக்கு|குரல் உள்ளீடு|வாசிக்கவும்|AI உதவியாளர்; மருத்துவர் அல்ல',
'hi':'अवलोकन|डैशबोर्ड|डेटासेट|पूर्वप्रसंस्करण|मॉडल प्रशिक्षण|क्वांटम सर्किट|मूल्यांकन|व्याख्या|अनुमान|प्रयोग|दस्तावेज़|शोध उपकरण|मेरे प्रतिभागी|मेरी रिपोर्ट|समीक्षा कतार|सहमति प्रयोगशाला|क्या होगा प्रयोगशाला|उपयोगकर्ता और नियुक्तियाँ|ऑडिट लॉग|माप|सहायक|सहमति|नाम|ईमेल|भूमिका|अनुमोदन|सटीकता|संवेदनशीलता|विशिष्टता|मॉडल|संभावना|भाषा|सक्रिय|जमा किया गया|समीक्षित|हाँ|नहीं|चुनें|बंद करें|अपरिभाषित|शोध अवलोकन|डेटा नमूने|इनपुट विशेषताएँ|प्रशिक्षित मॉडल|श्रेष्ठ ROC–AUC|प्रतिभागी पोर्टल|डॉक्टर पोर्टल|पूरा नाम|ईमेल पता|पासवर्ड|खाता बनाएँ|सुरक्षित साइन इन|साइन आउट|अपना खाता बनाएँ|फिर स्वागत है।|नया प्रयोग|डॉक्टर|प्रतिभागी|नियुक्ति सहेजें|डॉक्टर अनुमोदित करें|आपकी सहमति महत्वपूर्ण है।|शोध प्रोटोटाइप|अनुरोध विफल|कृपया प्रतीक्षा करें…|PDF रिपोर्ट डाउनलोड करें|बेंचमार्क नमूना लोड करें|अनुमान चलाएँ|मॉडल चुनें|शोध डेटासेट|शोध रिपोर्ट|कार्यस्थान खोलें|शोध रिपोर्ट बनाएँ|कृत्रिम उदाहरण भरें|समीक्षा नोट|नोट सहेजें|रिपोर्ट अनुमोदित करें|शोध सहमति|सहमति|असहमति|मेरा परिणाम समझाएँ|विश्वास का क्या अर्थ है?|डॉक्टर से क्या पूछूँ?|संदेश भेजें|चैट इतिहास हटाएँ|आवाज इनपुट|जोर से पढ़ें|AI सहायक, डॉक्टर नहीं',
'te':'అవలోకనం|డాష్‌బోర్డ్|డేటాసెట్లు|ముందస్తు ప్రాసెసింగ్|మోడల్ శిక్షణ|క్వాంటం సర్క్యూట్|మూల్యాంకనం|వివరణ|అంచనాలు|ప్రయోగాలు|పత్రాలు|పరిశోధన సాధనాలు|నా పాల్గొనేవారు|నా నివేదికలు|సమీక్ష వరుస|ఏకాభిప్రాయ ప్రయోగశాల|మార్పు ప్రయోగశాల|వినియోగదారులు మరియు కేటాయింపులు|ఆడిట్ లాగ్|కొలతలు|సహాయకుడు|సమ్మతి|పేరు|ఇమెయిల్|పాత్ర|ఆమోదం|ఖచ్చితత్వం|సున్నితత్వం|నిర్దిష్టత|మోడల్|సంభావ్యత|భాష|క్రియాశీలం|సమర్పించబడింది|సమీక్షించబడింది|అవును|కాదు|ఎంచుకోండి|మూసివేయి|నిర్వచించబడలేదు|పరిశోధన అవలోకనం|డేటా నమూనాలు|ఇన్‌పుట్ లక్షణాలు|శిక్షణ పొందిన మోడల్స్|ఉత్తమ ROC–AUC|పాల్గొనేవారి పోర్టల్|వైద్యుల పోర్టల్|పూర్తి పేరు|ఇమెయిల్ చిరునామా|పాస్‌వర్డ్|ఖాతా సృష్టించు|సురక్షితంగా సైన్ ఇన్|సైన్ అవుట్|మీ ఖాతా సృష్టించండి|మళ్లీ స్వాగతం.|కొత్త ప్రయోగం|వైద్యుడు|పాల్గొనేవారు|కేటాయింపు సేవ్ చేయి|వైద్యుడిని ఆమోదించు|మీ సమ్మతి ముఖ్యం.|పరిశోధన నమూనా|అభ్యర్థన విఫలమైంది|దయచేసి వేచి ఉండండి…|PDF నివేదిక ఎగుమతి|బెంచ్‌మార్క్ నమూనా లోడ్ చేయి|అంచనా నడుపు|మోడల్ ఎంచుకోండి|పరిశోధన డేటాసెట్|పరిశోధన నివేదిక|వర్క్‌స్పేస్ తెరవండి|పరిశోధన నివేదిక సృష్టించు|కృత్రిమ ఉదాహరణ నింపండి|సమీక్ష గమనిక|గమనిక సేవ్ చేయి|నివేదిక ఆమోదించు|పరిశోధన ఏకాభిప్రాయం|ఏకాభిప్రాయం|భేదాభిప్రాయం|నా ఫలితాన్ని వివరించండి|విశ్వాసం అంటే ఏమిటి?|వైద్యుడిని ఏమి అడగాలి?|సందేశం పంపు|చాట్ చరిత్ర తొలగించు|వాయిస్ ఇన్‌పుట్|చదవండి|AI సహాయకుడు, వైద్యుడు కాదు',
'ml':'അവലോകനം|ഡാഷ്ബോർഡ്|ഡാറ്റാസെറ്റുകൾ|മുൻപ്രോസസ്സിംഗ്|മാതൃക പരിശീലനം|ക്വാണ്ടം സർക്യൂട്ട്|മൂല്യനിർണയം|വിശദീകരണം|കണക്കുകൾ|പരീക്ഷണങ്ങൾ|രേഖകൾ|ഗവേഷണ ഉപകരണങ്ങൾ|എന്റെ പങ്കാളികൾ|എന്റെ റിപ്പോർട്ടുകൾ|പരിശോധന പട്ടിക|സമ്മത ലാബ്|മാറ്റം ലാബ്|ഉപയോക്താക്കളും നിയോഗങ്ങളും|ഓഡിറ്റ് രേഖ|അളവുകൾ|സഹായി|സമ്മതം|പേര്|ഇമെയിൽ|പങ്ക്|അംഗീകാരം|കൃത്യത|സെൻസിറ്റിവിറ്റി|സ്പെസിഫിസിറ്റി|മാതൃക|സാധ്യത|ഭാഷ|സജീവം|സമർപ്പിച്ചു|പരിശോധിച്ചു|അതെ|ഇല്ല|തിരഞ്ഞെടുക്കുക|അടയ്ക്കുക|നിർവചിച്ചിട്ടില്ല|ഗവേഷണ അവലോകനം|ഡാറ്റാ സാമ്പിളുകൾ|ഇൻപുട്ട് സവിശേഷതകൾ|പരിശീലിച്ച മാതൃകകൾ|മികച്ച ROC–AUC|പങ്കാളി പോർട്ടൽ|ഡോക്ടർ പോർട്ടൽ|മുഴുവൻ പേര്|ഇമെയിൽ വിലാസം|പാസ്‌വേഡ്|അക്കൗണ്ട് സൃഷ്ടിക്കുക|സുരക്ഷിത സൈൻ ഇൻ|സൈൻ ഔട്ട്|നിങ്ങളുടെ അക്കൗണ്ട് സൃഷ്ടിക്കുക|വീണ്ടും സ്വാഗതം.|പുതിയ പരീക്ഷണം|ഡോക്ടർ|പങ്കാളി|നിയോഗം സംരക്ഷിക്കുക|ഡോക്ടറെ അംഗീകരിക്കുക|നിങ്ങളുടെ സമ്മതം പ്രധാനമാണ്.|ഗവേഷണ മാതൃക|അഭ്യർത്ഥന പരാജയപ്പെട്ടു|കാത്തിരിക്കുക…|PDF റിപ്പോർട്ട് ഡൗൺലോഡ്|സാമ്പിൾ ലോഡ് ചെയ്യുക|കണക്ക് പ്രവർത്തിപ്പിക്കുക|മാതൃക തിരഞ്ഞെടുക്കുക|ഗവേഷണ ഡാറ്റാസെറ്റ്|ഗവേഷണ റിപ്പോർട്ട്|വർക്ക്‌സ്‌പേസ് തുറക്കുക|ഗവേഷണ റിപ്പോർട്ട് സൃഷ്ടിക്കുക|കൃത്രിമ ഉദാഹരണം നിറയ്ക്കുക|പരിശോധന കുറിപ്പ്|കുറിപ്പ് സംരക്ഷിക്കുക|റിപ്പോർട്ട് അംഗീകരിക്കുക|ഗവേഷണ സമ്മതം|സമ്മതി|വിയോജിപ്പ്|എന്റെ ഫലം വിശദീകരിക്കുക|വിശ്വാസം എന്താണ്?|ഡോക്ടറോട് എന്ത് ചോദിക്കണം?|സന്ദേശം അയയ്ക്കുക|ചാറ്റ് ചരിത്രം നീക്കുക|ശബ്ദ ഇൻപുട്ട്|ഉറക്കെ വായിക്കുക|AI സഹായി, ഡോക്ടർ അല്ല',
'kn':'ಅವಲೋಕನ|ಡ್ಯಾಶ್‌ಬೋರ್ಡ್|ಡೇಟಾಸೆಟ್‌ಗಳು|ಪೂರ್ವ ಸಂಸ್ಕರಣೆ|ಮಾದರಿ ತರಬೇತಿ|ಕ್ವಾಂಟಂ ಸರ್ಕ್ಯೂಟ್|ಮೌಲ್ಯಮಾಪನ|ವಿವರಣೆ|ಅಂದಾಜುಗಳು|ಪ್ರಯೋಗಗಳು|ದಾಖಲೆಗಳು|ಸಂಶೋಧನಾ ಸಾಧನಗಳು|ನನ್ನ ಭಾಗವಹಿಸುವವರು|ನನ್ನ ವರದಿಗಳು|ಪರಿಶೀಲನೆ ಸಾಲು|ಒಮ್ಮತ ಪ್ರಯೋಗಾಲಯ|ಬದಲಾವಣೆ ಪ್ರಯೋಗಾಲಯ|ಬಳಕೆದಾರರು ಮತ್ತು ನಿಯೋಜನೆಗಳು|ಆಡಿಟ್ ದಾಖಲೆ|ಅಳತೆಗಳು|ಸಹಾಯಕ|ಸಮ್ಮತಿ|ಹೆಸರು|ಇಮೇಲ್|ಪಾತ್ರ|ಅನುಮೋದನೆ|ನಿಖರತೆ|ಸೂಕ್ಷ್ಮತೆ|ನಿರ್ದಿಷ್ಟತೆ|ಮಾದರಿ|ಸಂಭಾವ್ಯತೆ|ಭಾಷೆ|ಸಕ್ರಿಯ|ಸಲ್ಲಿಸಲಾಗಿದೆ|ಪರಿಶೀಲಿಸಲಾಗಿದೆ|ಹೌದು|ಇಲ್ಲ|ಆಯ್ಕೆ|ಮುಚ್ಚಿ|ವ್ಯಾಖ್ಯಾನಿಸಿಲ್ಲ|ಸಂಶೋಧನಾ ಅವಲೋಕನ|ಡೇಟಾ ಮಾದರಿಗಳು|ಇನ್‌ಪುಟ್ ಲಕ್ಷಣಗಳು|ತರಬೇತಿಯಾದ ಮಾದರಿಗಳು|ಅತ್ಯುತ್ತಮ ROC–AUC|ಭಾಗವಹಿಸುವವರ ಪೋರ್ಟಲ್|ವೈದ್ಯರ ಪೋರ್ಟಲ್|ಪೂರ್ಣ ಹೆಸರು|ಇಮೇಲ್ ವಿಳಾಸ|ಪಾಸ್‌ವರ್ಡ್|ಖಾತೆ ರಚಿಸಿ|ಸುರಕ್ಷಿತ ಸೈನ್ ಇನ್|ಸೈನ್ ಔಟ್|ನಿಮ್ಮ ಖಾತೆ ರಚಿಸಿ|ಮತ್ತೆ ಸ್ವಾಗತ.|ಹೊಸ ಪ್ರಯೋಗ|ವೈದ್ಯರು|ಭಾಗವಹಿಸುವವರು|ನಿಯೋಜನೆ ಉಳಿಸಿ|ವೈದ್ಯರನ್ನು ಅನುಮೋದಿಸಿ|ನಿಮ್ಮ ಸಮ್ಮತಿ ಮುಖ್ಯ.|ಸಂಶೋಧನಾ ಮಾದರಿ|ವಿನಂತಿ ವಿಫಲ|ದಯವಿಟ್ಟು ಕಾಯಿರಿ…|PDF ವರದಿ ರಫ್ತು|ಮಾನದಂಡದ ಮಾದರಿ ಲೋಡ್|ಅಂದಾಜು ಚಲಾಯಿಸಿ|ಮಾದರಿ ಆಯ್ಕೆ|ಸಂಶೋಧನಾ ಡೇಟಾಸೆಟ್|ಸಂಶೋಧನಾ ವರದಿ|ಕಾರ್ಯಸ್ಥಳ ತೆರೆಯಿರಿ|ಸಂಶೋಧನಾ ವರದಿ ರಚಿಸಿ|ಕೃತಕ ಉದಾಹರಣೆ ತುಂಬಿಸಿ|ಪರಿಶೀಲನೆ ಟಿಪ್ಪಣಿ|ಟಿಪ್ಪಣಿ ಉಳಿಸಿ|ವರದಿ ಅನುಮೋದಿಸಿ|ಸಂಶೋಧನಾ ಒಮ್ಮತ|ಒಮ್ಮತ|ಭಿನ್ನಾಭಿಪ್ರಾಯ|ನನ್ನ ಫಲಿತಾಂಶ ವಿವರಿಸಿ|ವಿಶ್ವಾಸ ಎಂದರೇನು?|ವೈದ್ಯರನ್ನು ಏನು ಕೇಳಬೇಕು?|ಸಂದೇಶ ಕಳುಹಿಸಿ|ಚಾಟ್ ಇತಿಹಾಸ ಅಳಿಸಿ|ಧ್ವನಿ ಇನ್‌ಪುಟ್|ಓದಿ|AI ಸಹಾಯಕ, ವೈದ್ಯರಲ್ಲ',
'es':'Resumen|Panel|Conjuntos de datos|Preprocesamiento|Entrenamiento de modelos|Circuito cuántico|Evaluación|Explicaciones|Predicciones|Experimentos|Documentación|Herramientas de investigación|Mis participantes|Mis informes|Cola de revisión|Laboratorio de consenso|Simulador de cambios|Usuarios y asignaciones|Registro de auditoría|Mediciones|Asistente|Consentimiento|Nombre|Correo|Rol|Aprobación|Exactitud|Sensibilidad|Especificidad|Modelo|Probabilidad|Idioma|Activo|Enviado|Revisado|Sí|No|Seleccionar|Cerrar|Indefinido|Resumen de investigación|Muestras de datos|Variables de entrada|Modelos entrenados|Mejor ROC–AUC|Portal del participante|Portal del médico|Nombre completo|Correo electrónico|Contraseña|Crear cuenta|Iniciar sesión segura|Cerrar sesión|Cree su cuenta|Bienvenido de nuevo.|Nuevo experimento|Médico|Participante|Guardar asignación|Aprobar médico|Su consentimiento importa.|Prototipo de investigación|Solicitud fallida|Espere…|Exportar informe PDF|Cargar muestra de referencia|Ejecutar predicción|Seleccionar modelo|Datos de investigación|Informe de investigación|Abrir espacio|Crear informe de investigación|Rellenar ejemplo sintético|Nota de revisión|Guardar nota|Aprobar informe|Consenso de investigación|Acuerdo|Desacuerdo|Explique mi resultado|¿Qué significa confianza?|¿Qué debo preguntar a mi médico?|Enviar mensaje|Eliminar historial|Entrada de voz|Leer en voz alta|Asistente de IA, no un médico',
'fr':'Aperçu|Tableau de bord|Jeux de données|Prétraitement|Entraînement des modèles|Circuit quantique|Évaluation|Explications|Prédictions|Expériences|Documentation|Outils de recherche|Mes participants|Mes rapports|File de révision|Laboratoire de consensus|Simulateur de changements|Utilisateurs et affectations|Journal d’audit|Mesures|Assistant|Consentement|Nom|Courriel|Rôle|Approbation|Exactitude|Sensibilité|Spécificité|Modèle|Probabilité|Langue|Actif|Soumis|Examiné|Oui|Non|Choisir|Fermer|Indéfini|Aperçu de la recherche|Échantillons|Variables d’entrée|Modèles entraînés|Meilleur ROC–AUC|Portail du participant|Portail du médecin|Nom complet|Adresse électronique|Mot de passe|Créer un compte|Connexion sécurisée|Déconnexion|Créez votre compte|Bon retour.|Nouvelle expérience|Médecin|Participant|Enregistrer l’affectation|Approuver le médecin|Votre consentement compte.|Prototype de recherche|Échec de la requête|Veuillez patienter…|Exporter le rapport PDF|Charger un exemple|Lancer la prédiction|Choisir un modèle|Données de recherche|Rapport de recherche|Ouvrir l’espace|Créer un rapport|Remplir un exemple synthétique|Note de révision|Enregistrer la note|Approuver le rapport|Consensus de recherche|Accord|Désaccord|Expliquez mon résultat|Que signifie la confiance ?|Que demander à mon médecin ?|Envoyer|Supprimer l’historique|Saisie vocale|Lire à voix haute|Assistant IA, pas un médecin',
'ar':'نظرة عامة|لوحة التحكم|مجموعات البيانات|المعالجة المسبقة|تدريب النماذج|الدائرة الكمية|التقييم|التفسيرات|التنبؤات|التجارب|التوثيق|أدوات البحث|المشاركون لدي|تقاريري|قائمة المراجعة|مختبر التوافق|محاكي التغييرات|المستخدمون والتعيينات|سجل التدقيق|القياسات|المساعد|الموافقة|الاسم|البريد|الدور|الاعتماد|الدقة|الحساسية|النوعية|النموذج|الاحتمال|اللغة|نشط|تم الإرسال|تمت المراجعة|نعم|لا|اختر|إغلاق|غير محدد|ملخص البحث|عينات البيانات|خصائص الإدخال|النماذج المدربة|أفضل ROC–AUC|بوابة المشارك|بوابة الطبيب|الاسم الكامل|البريد الإلكتروني|كلمة المرور|إنشاء حساب|تسجيل دخول آمن|تسجيل الخروج|أنشئ حسابك|مرحبًا بعودتك.|تجربة جديدة|الطبيب|المشارك|حفظ التعيين|اعتماد الطبيب|موافقتك مهمة.|نموذج بحثي أولي|فشل الطلب|يرجى الانتظار…|تصدير تقرير PDF|تحميل عينة مرجعية|تشغيل التنبؤ|اختر نموذجًا|بيانات البحث|تقرير البحث|فتح مساحة العمل|إنشاء تقرير بحثي|ملء مثال اصطناعي|ملاحظة المراجعة|حفظ الملاحظة|اعتماد التقرير|توافق البحث|اتفاق|اختلاف|اشرح نتيجتي|ما معنى الثقة؟|ماذا أسأل طبيبي؟|إرسال رسالة|حذف سجل المحادثة|إدخال صوتي|قراءة بصوت عالٍ|مساعد ذكاء اصطناعي وليس طبيبًا'
}
backend=json.loads((root/'backend/i18n/messages.json').read_text(encoding='utf-8'))
for language,values in translations.items():
    items=values.split('|')
    assert len(items)==len(keys),(language,len(items),len(keys))
    catalog={**en,**dict(zip(keys,items))}
    catalog['Research prototype. Not for diagnosis or treatment.']=backend[language]['research']
    catalog['AI assistant, not a doctor']=backend[language]['disclaimer']
    # English technical/descriptive fallback is deliberate until domain translation review.
    (root/f'src/research/locales/{language}.json').write_text(json.dumps(catalog,ensure_ascii=False,indent=2),encoding='utf-8')
print('Generated nine catalogs; specialized technical descriptions retain explicit English fallback.')
